const jsonHeaders={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...jsonHeaders,...extra}})}
function slugify(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')}
function clean(v,max=1000000){return v==null?'':String(v).trim().slice(0,max)}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}
function sanitize(v){let h=String(v||'').replace(/<!--[\s\S]*?-->/g,'');h=h.replace(/<\s*(script|iframe|object|embed|form|input|textarea|button|meta|link|style)[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi,'').replace(/<\s*(script|iframe|object|embed|form|input|textarea|button|meta|link|style)[^>]*\/?\s*>/gi,'');const ok=/^(p|br|h2|h3|h4|strong|b|em|i|u|s|ul|ol|li|blockquote|a|img|div|span)$/i;h=h.replace(/<\/?([a-z0-9]+)([^>]*)>/gi,(full,tag,attrs)=>{if(!ok.test(tag))return '';if(full.startsWith('</'))return `</${tag.toLowerCase()}>`;let out='',m;const re=/([a-zA-Z-]+)\s*=\s*(?:\"([^\"]*)\"|'([^']*)'|([^\s>]+))/g;while((m=re.exec(attrs))){const n=m[1].toLowerCase(),val=m[2]??m[3]??m[4]??'';if(/^on/i.test(n))continue;if(n==='style'){const good=val.split(';').map(x=>x.trim()).filter(x=>/^(color|background-color|font-weight|text-align)\s*:\s*[-#(),.%\w\s]+$/i.test(x));if(good.length)out+=` style="${esc(good.join('; '))}"`;continue}if(n==='href'){if(/^https?:\/\//i.test(val)||val.startsWith('/'))out+=` href="${esc(val)}" target="_blank" rel="noopener noreferrer"`;continue}if(n==='src'){if(/^https?:\/\//i.test(val)||val.startsWith('/api/media/'))out+=` src="${esc(val)}"`;continue}if(['alt','title','width','height'].includes(n))out+=` ${n}="${esc(val.slice(0,500))}"`}return tag.toLowerCase()==='img'?`<img${out}>`:tag.toLowerCase()==='br'?'<br>':`<${tag.toLowerCase()}${out}>`});return h.slice(0,1000000)}
function contentHtml(v){const s=String(v||'');if(/<\s*(p|h2|h3|ul|ol|blockquote|img|strong|em|div)\b/i.test(s))return sanitize(s);return esc(s).split(/\n\s*\n/).map(p=>p.trim()?`<p>${p.replace(/\n/g,'<br>')}</p>`:'').join('')}
async function body(request){try{return await request.json()}catch{return null}}
async function auth(request,env){const p=request.headers.get('X-Admin-Password');return Boolean(p&&env.ADMIN_PASSWORD&&p===env.ADMIN_PASSWORD)}
const noauth=()=>json({success:false,error:'Unauthorized.'},401);
async function ensureCmsTables(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS media (id INTEGER PRIMARY KEY AUTOINCREMENT,filename TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,mime_type TEXT NOT NULL,size INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),env.DB.prepare(`INSERT OR IGNORE INTO site_settings(key,value) VALUES('site_name','"FigureNG"'),('site_tagline','"Practical tools and information for Nigeria."'),('nav_items','[{"label":"Tools","url":"/tools.html","enabled":true},{"label":"Guides","url":"/guides.html","enabled":true},{"label":"About","url":"/about.html","enabled":true}]')`)]).catch(()=>{} )}
async function articles(request,env){const u=new URL(request.url),slug=u.searchParams.get('slug');if(slug){const a=await env.DB.prepare(`SELECT id,title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at,created_at,updated_at FROM articles WHERE slug=? AND status='published' LIMIT 1`).bind(slug).first();return a?json({success:true,article:a}):json({success:false,error:'Article not found.'},404)}const status=u.searchParams.get('status')||'published',limit=Math.min(Math.max(Number(u.searchParams.get('limit')||20)||20,1),100),where=status==='all'?'':'WHERE status=?',binds=status==='all'?[limit]:[status,limit];const r=await env.DB.prepare(`SELECT id,title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at,created_at,updated_at FROM articles ${where} ORDER BY COALESCE(published_at,created_at) DESC LIMIT ?`).bind(...binds).all();return json({success:true,count:r.results.length,articles:r.results})}
async function one(id,env){const a=await env.DB.prepare(`SELECT id,title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at,created_at,updated_at FROM articles WHERE id=? LIMIT 1`).bind(Number(id)).first();return a?json({success:true,article:a}):json({success:false,error:'Article not found.'},404)}
async function create(request,env){const b=await body(request);if(!b)return json({success:false,error:'Invalid JSON request.'},400);const title=clean(b.title,200),content=contentHtml(b.content),excerpt=clean(b.excerpt,500),category=clean(b.category,100)||'Guides',image=clean(b.featured_image,1000),seo=clean(b.seo_title,200),meta=clean(b.meta_description,320);if(!title||!content.replace(/<[^>]*>/g,'').trim())return json({success:false,error:'Title and content are required.'},400);let slug=slugify(b.slug||title);if(!slug)return json({success:false,error:'A valid article slug is required.'},400);if(await env.DB.prepare('SELECT id FROM articles WHERE slug=? LIMIT 1').bind(slug).first())slug+='-'+Date.now();const status=b.status==='published'?'published':'draft',published=status==='published'?new Date().toISOString():null,r=await env.DB.prepare(`INSERT INTO articles(title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(title,slug,excerpt,content,category,image,seo,meta,status,published).run();return json({success:true,message:'Article created successfully.',article:{id:r.meta.last_row_id,title,slug,status,url:`/article.html?slug=${encodeURIComponent(slug)}`}},201)}
async function update(id,request,env){const aid=Number(id);if(!Number.isInteger(aid)||aid<=0)return json({success:false,error:'Invalid article ID.'},400);const b=await body(request);if(!b)return json({success:false,error:'Invalid JSON request.'},400);const cur=await env.DB.prepare('SELECT status,published_at FROM articles WHERE id=?').bind(aid).first();if(!cur)return json({success:false,error:'Article not found.'},404);const title=clean(b.title,200),content=contentHtml(b.content),excerpt=clean(b.excerpt,500),category=clean(b.category,100)||'Guides',image=clean(b.featured_image,1000),seo=clean(b.seo_title,200),meta=clean(b.meta_description,320);if(!title||!content.replace(/<[^>]*>/g,'').trim())return json({success:false,error:'Title and content are required.'},400);let slug=slugify(b.slug||title);const dup=await env.DB.prepare('SELECT id FROM articles WHERE slug=? AND id!=? LIMIT 1').bind(slug,aid).first();if(dup)slug+='-'+Date.now();const status=b.status==='published'?'published':'draft';let published=cur.published_at;if(status==='published'&&!published)published=new Date().toISOString();if(status==='draft')published=null;await env.DB.prepare(`UPDATE articles SET title=?,slug=?,excerpt=?,content=?,category=?,featured_image=?,seo_title=?,meta_description=?,status=?,published_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(title,slug,excerpt,content,category,image,seo,meta,status,published,aid).run();return json({success:true,message:'Article updated successfully.',article:{id:aid,title,slug,status,url:`/article.html?slug=${encodeURIComponent(slug)}`}})}
async function remove(id,env){const r=await env.DB.prepare('DELETE FROM articles WHERE id=?').bind(Number(id)).run();return r.meta.changes?json({success:true,message:'Article deleted successfully.'}):json({success:false,error:'Article not found.'},404)}
const defaultNav=[{label:'Tools',url:'/tools.html',enabled:true},{label:'Guides',url:'/guides.html',enabled:true},{label:'About',url:'/about.html',enabled:true}];
async function settings(env){const r=await env.DB.prepare('SELECT key,value FROM site_settings').all(),s={};for(const x of r.results){try{s[x.key]=JSON.parse(x.value)}catch{s[x.key]=x.value}}if(!Array.isArray(s.nav_items))s.nav_items=defaultNav;return s}
async function putSettings(request,env){const b=await body(request);if(!b||!b.settings)return json({success:false,error:'Settings are required.'},400);const s=b.settings,n={site_name:String(s.site_name||'FigureNG').slice(0,100),site_tagline:String(s.site_tagline||'').slice(0,300),nav_items:Array.isArray(s.nav_items)?s.nav_items.slice(0,12).map(x=>({label:String(x.label||'').slice(0,50),url:String(x.url||'').slice(0,300),enabled:Boolean(x.enabled)})):defaultNav};for(const [k,v] of Object.entries(n))await env.DB.prepare('INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(k,JSON.stringify(v)).run();return json({success:true,message:'Site settings saved.',settings:n})}
function allowedImage(t){return ['image/jpeg','image/png','image/webp','image/gif','image/svg+xml'].includes(t)}
async function upload(request,env){if(!env.MEDIA)return json({success:false,error:'Image storage is not configured. Create the figureng-media R2 bucket, then deploy again.'},503);const f=(await request.formData()).get('file');if(!(f instanceof File))return json({success:false,error:'No image file was uploaded.'},400);if(!allowedImage(f.type))return json({success:false,error:'Only JPG, PNG, WebP, GIF and SVG images are allowed.'},400);if(f.size>5*1024*1024)return json({success:false,error:'Image must be 5 MB or smaller.'},400);const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',key=`articles/${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.MEDIA.put(key,f.stream(),{httpMetadata:{contentType:f.type,cacheControl:'public, max-age=31536000, immutable'}});await env.DB.prepare('INSERT INTO media(filename,object_key,mime_type,size) VALUES(?,?,?,?)').bind(f.name,key,f.type,f.size).run();return json({success:true,url:`/api/media/${encodeURIComponent(key)}`,key,filename:f.name})}
async function media(key,env){if(!env.MEDIA)return new Response('Media storage is not configured.',{status:503});const o=await env.MEDIA.get(key);if(!o)return new Response('Image not found',{status:404});const h=new Headers();o.writeHttpMetadata(h);h.set('etag',o.httpEtag);h.set('Cache-Control','public, max-age=31536000, immutable');return new Response(o.body,{headers:h})}
async function assets(request,env){const r=await env.ASSETS.fetch(request);const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))return r;const text=await r.text();if(!text.toLowerCase().includes('</body>'))return new Response(text,r);const injected=text.replace(/<\/body>/i,'<script src="/site-config.js" defer></script></body>');const h=new Headers(r.headers);h.delete('content-length');return new Response(injected,{status:r.status,statusText:r.statusText,headers:h})}
export default {async fetch(request,env){const u=new URL(request.url),p=u.pathname;try{await ensureCmsTables(env);if(p.startsWith('/api/media/'))return media(decodeURIComponent(p.slice(11)),env);if(p==='/api/site-config'&&request.method==='GET')return json({success:true,settings:await settings(env)});if(p==='/api/articles'&&request.method==='GET')return articles(request,env);if(p.startsWith('/api/')){if(!(await auth(request,env)))return noauth();if(p==='/api/articles'&&request.method==='POST')return create(request,env);if(p==='/api/media'&&request.method==='POST')return upload(request,env);if(p==='/api/site-config'&&request.method==='PUT')return putSettings(request,env);const m=p.match(/^\/api\/articles\/(\d+)$/);if(m){if(request.method==='GET')return one(m[1],env);if(request.method==='PUT')return update(m[1],request,env);if(request.method==='DELETE')return remove(m[1],env)}}return assets(request,env)}catch(e){return json({success:false,error:e?.message||'Server error.'},500)}}};
