const jsonHeaders={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...jsonHeaders,...extra}})}
function slugify(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')}
function clean(v,max=1000000){return v==null?'':String(v).trim().slice(0,max)}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}
function sanitize(v){let h=String(v||'').replace(/<!--[\s\S]*?-->/g,'');h=h.replace(/<\s*(script|iframe|object|embed|form|input|textarea|button|meta|link|style)[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi,'').replace(/<\s*(script|iframe|object|embed|form|input|textarea|button|meta|link|style)[^>]*\/?\s*>/gi,'');const ok=/^(p|br|h2|h3|h4|strong|b|em|i|u|s|ul|ol|li|blockquote|a|img|div|span)$/i;h=h.replace(/<\/?([a-z0-9]+)([^>]*)>/gi,(full,tag,attrs)=>{if(!ok.test(tag))return '';if(full.startsWith('</'))return `</${tag.toLowerCase()}>`;let out='',m;const re=/([a-zA-Z-]+)\s*=\s*(?:\"([^\"]*)\"|'([^']*)'|([^\s>]+))/g;while((m=re.exec(attrs))){const n=m[1].toLowerCase(),val=m[2]??m[3]??m[4]??'';if(/^on/i.test(n))continue;if(n==='style'){const good=val.split(';').map(x=>x.trim()).filter(x=>/^(color|background-color|font-weight|text-align)\s*:\s*[-#(),.%\w\s]+$/i.test(x));if(good.length)out+=` style=\"${esc(good.join('; '))}\"`;continue}if(n==='href'){if(/^https?:\/\//i.test(val)||val.startsWith('/'))out+=` href=\"${esc(val)}\" target=\"_blank\" rel=\"noopener noreferrer\"`;continue}if(n==='src'){if(/^https?:\/\//i.test(val)||val.startsWith('/api/media/'))out+=` src=\"${esc(val)}\"`;continue}if(['alt','title','width','height'].includes(n))out+=` ${n}=\"${esc(val.slice(0,500))}\"`}return tag.toLowerCase()==='img'?`<img${out}>`:tag.toLowerCase()==='br'?'<br>':`<${tag.toLowerCase()}${out}>`});return h.slice(0,1000000)}
function contentHtml(v){const s=String(v||'');if(/<\s*(p|h2|h3|ul|ol|blockquote|img|strong|em|div)\b/i.test(s))return sanitize(s);return esc(s).split(/\n\s*\n/).map(p=>p.trim()?`<p>${p.replace(/\n/g,'<br>')}</p>`:'').join('')}
async function body(request){try{return await request.json()}catch{return null}}
async function auth(request,env){const p=request.headers.get('X-Admin-Password');return Boolean(p&&env.ADMIN_PASSWORD&&p===env.ADMIN_PASSWORD)}
const noauth=()=>json({success:false,error:'Unauthorized.'},401);

async function ensureCmsTables(env){
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS media (id INTEGER PRIMARY KEY AUTOINCREMENT,filename TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,mime_type TEXT NOT NULL,size INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  try{await env.DB.prepare(`ALTER TABLE media ADD COLUMN data TEXT NOT NULL DEFAULT ''`).run()}catch{}
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS analytics_events (id INTEGER PRIMARY KEY AUTOINCREMENT,event_name TEXT NOT NULL,path TEXT NOT NULL DEFAULT '',title TEXT DEFAULT '',referrer TEXT DEFAULT '',country TEXT DEFAULT '',visitor_id TEXT DEFAULT '',session_id TEXT DEFAULT '',duration_ms INTEGER DEFAULT 0,metadata TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_analytics_created_at ON analytics_events(created_at)`).run();
  await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_analytics_event_name ON analytics_events(event_name)`).run();
  await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_analytics_path ON analytics_events(path)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS ad_settings (id INTEGER PRIMARY KEY CHECK (id=1),enabled INTEGER NOT NULL DEFAULT 0,publisher_id TEXT NOT NULL DEFAULT '',top_slot TEXT NOT NULL DEFAULT '',content_slot TEXT NOT NULL DEFAULT '',sidebar_slot TEXT NOT NULL DEFAULT '',bottom_slot TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`INSERT OR IGNORE INTO ad_settings(id) VALUES(1)`).run();
  await env.DB.prepare(`INSERT OR IGNORE INTO site_settings(key,value) VALUES('site_name','\"FigureNG\"')`).run();
  await env.DB.prepare(`INSERT OR IGNORE INTO site_settings(key,value) VALUES('site_tagline','\"Practical tools and information for Nigeria.\"')`).run();
  await env.DB.prepare(`INSERT OR IGNORE INTO site_settings(key,value) VALUES('nav_items','[{\"label\":\"Tools\",\"url\":\"/tools.html\",\"enabled\":true},{\"label\":\"Guides\",\"url\":\"/guides.html\",\"enabled\":true},{\"label\":\"About\",\"url\":\"/about.html\",\"enabled\":true}]')`).run();
}
async function articles(request,env){const u=new URL(request.url),slug=u.searchParams.get('slug');if(slug){const a=await env.DB.prepare(`SELECT id,title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at,created_at,updated_at FROM articles WHERE slug=? AND status='published' LIMIT 1`).bind(slug).first();return a?json({success:true,article:a}):json({success:false,error:'Article not found.'},404)}const status=u.searchParams.get('status')||'published',limit=Math.min(Math.max(Number(u.searchParams.get('limit')||20)||20,1),100),where=status==='all'?'':'WHERE status=?',binds=status==='all'?[limit]:[status,limit];const r=await env.DB.prepare(`SELECT id,title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at,created_at,updated_at FROM articles ${where} ORDER BY COALESCE(published_at,created_at) DESC LIMIT ?`).bind(...binds).all();return json({success:true,count:r.results.length,articles:r.results})}
async function one(id,env){const a=await env.DB.prepare(`SELECT id,title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at,created_at,updated_at FROM articles WHERE id=? LIMIT 1`).bind(Number(id)).first();return a?json({success:true,article:a}):json({success:false,error:'Article not found.'},404)}
async function create(request,env){const b=await body(request);if(!b)return json({success:false,error:'Invalid JSON request.'},400);const title=clean(b.title,200),content=contentHtml(b.content),excerpt=clean(b.excerpt,500),category=clean(b.category,100)||'Guides',image=clean(b.featured_image,1000),seo=clean(b.seo_title,200),meta=clean(b.meta_description,320);if(!title||!content.replace(/<[^>]*>/g,'').trim())return json({success:false,error:'Title and content are required.'},400);let slug=slugify(b.slug||title);if(!slug)return json({success:false,error:'A valid article slug is required.'},400);if(await env.DB.prepare('SELECT id FROM articles WHERE slug=? LIMIT 1').bind(slug).first())slug+='-'+Date.now();const status=b.status==='published'?'published':'draft',published=status==='published'?new Date().toISOString():null,r=await env.DB.prepare(`INSERT INTO articles(title,slug,excerpt,content,category,featured_image,seo_title,meta_description,status,published_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(title,slug,excerpt,content,category,image,seo,meta,status,published).run();return json({success:true,message:'Article created successfully.',article:{id:r.meta.last_row_id,title,slug,status,url:`/article.html?slug=${encodeURIComponent(slug)}`}},201)}
async function update(id,request,env){const aid=Number(id);if(!Number.isInteger(aid)||aid<=0)return json({success:false,error:'Invalid article ID.'},400);const b=await body(request);if(!b)return json({success:false,error:'Invalid JSON request.'},400);const cur=await env.DB.prepare('SELECT status,published_at FROM articles WHERE id=?').bind(aid).first();if(!cur)return json({success:false,error:'Article not found.'},404);const title=clean(b.title,200),content=contentHtml(b.content),excerpt=clean(b.excerpt,500),category=clean(b.category,100)||'Guides',image=clean(b.featured_image,1000),seo=clean(b.seo_title,200),meta=clean(b.meta_description,320);if(!title||!content.replace(/<[^>]*>/g,'').trim())return json({success:false,error:'Title and content are required.'},400);let slug=slugify(b.slug||title);const dup=await env.DB.prepare('SELECT id FROM articles WHERE slug=? AND id!=? LIMIT 1').bind(slug,aid).first();if(dup)slug+='-'+Date.now();const status=b.status==='published'?'published':'draft';let published=cur.published_at;if(status==='published'&&!published)published=new Date().toISOString();if(status==='draft')published=null;await env.DB.prepare(`UPDATE articles SET title=?,slug=?,excerpt=?,content=?,category=?,featured_image=?,seo_title=?,meta_description=?,status=?,published_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(title,slug,excerpt,category,image,seo,meta,status,published,aid).run();return json({success:true,message:'Article updated successfully.',article:{id:aid,title,slug,status,url:`/article.html?slug=${encodeURIComponent(slug)}`}})}
async function remove(id,env){const r=await env.DB.prepare('DELETE FROM articles WHERE id=?').bind(Number(id)).run();return r.meta.changes?json({success:true,message:'Article deleted successfully.'}):json({success:false,error:'Article not found.'},404)}
const defaultNav=[{label:'Tools',url:'/tools.html',enabled:true},{label:'Guides',url:'/guides.html',enabled:true},{label:'About',url:'/about.html',enabled:true}];
async function settings(env){const r=await env.DB.prepare('SELECT key,value FROM site_settings').all(),s={};for(const x of r.results){try{s[x.key]=JSON.parse(x.value)}catch{s[x.key]=x.value}}if(!Array.isArray(s.nav_items))s.nav_items=defaultNav;const a=await env.DB.prepare('SELECT enabled,publisher_id,top_slot,content_slot,sidebar_slot,bottom_slot FROM ad_settings WHERE id=1').first();s.ads={enabled:Boolean(a?.enabled),publisher_id:a?.publisher_id||'',top_slot:a?.top_slot||'',content_slot:a?.content_slot||'',sidebar_slot:a?.sidebar_slot||'',bottom_slot:a?.bottom_slot||''};return s}
async function putSettings(request,env){const b=await body(request);if(!b||!b.settings)return json({success:false,error:'Settings are required.'},400);const s=b.settings,n={site_name:String(s.site_name||'FigureNG').slice(0,100),site_tagline:String(s.site_tagline||'').slice(0,300),nav_items:Array.isArray(s.nav_items)?s.nav_items.slice(0,12).map(x=>({label:String(x.label||'').slice(0,50),url:String(x.url||'').slice(0,300),enabled:Boolean(x.enabled)})):defaultNav};for(const [k,v] of Object.entries(n))await env.DB.prepare('INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(k,JSON.stringify(v)).run();return json({success:true,message:'Site settings saved.',settings:n})}
async function putAds(request,env){const b=await body(request);const a=b?.ads;if(!a)return json({success:false,error:'Ad settings are required.'},400);const cleanSlot=v=>String(v||'').replace(/[^0-9]/g,'').slice(0,30);await env.DB.prepare(`INSERT INTO ad_settings(id,enabled,publisher_id,top_slot,content_slot,sidebar_slot,bottom_slot,updated_at) VALUES(1,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET enabled=excluded.enabled,publisher_id=excluded.publisher_id,top_slot=excluded.top_slot,content_slot=excluded.content_slot,sidebar_slot=excluded.sidebar_slot,bottom_slot=excluded.bottom_slot,updated_at=CURRENT_TIMESTAMP`).bind(a.enabled?1:0,String(a.publisher_id||'').slice(0,100),cleanSlot(a.top_slot),cleanSlot(a.content_slot),cleanSlot(a.sidebar_slot),cleanSlot(a.bottom_slot)).run();return json({success:true,message:'Ad settings saved.'})}
async function analyticsWrite(request,env){const b=await body(request);if(!b||!b.event)return json({success:false,error:'Event required.'},400);const event=String(b.event).slice(0,40),path=String(b.path||'').slice(0,500),title=String(b.title||'').slice(0,200),ref=String(b.referrer||'').slice(0,500),visitor=String(b.visitor_id||'').slice(0,100),session=String(b.session_id||'').slice(0,100),duration=Math.min(Math.max(Number(b.duration_ms)||0,0),86400000),metadata=String(b.metadata||'').slice(0,2000),country=String(request.cf?.country||'').slice(0,10);if(!visitor||!session)return json({success:true});await env.DB.prepare(`INSERT INTO analytics_events(event_name,path,title,referrer,country,visitor_id,session_id,duration_ms,metadata) VALUES(?,?,?,?,?,?,?,?,?)`).bind(event,path,title,ref,country,visitor,session,duration,metadata).run();return json({success:true})}
async function analyticsReport(request,env){const u=new URL(request.url),days=Math.min(Math.max(Number(u.searchParams.get('days')||30)||30,1),365),since=new Date(Date.now()-days*86400000).toISOString();const [views,visitors,sessions,top,countries,events,duration]=await Promise.all([
 env.DB.prepare(`SELECT COUNT(*) n FROM analytics_events WHERE event_name='page_view' AND created_at>=?`).bind(since).first(),
 env.DB.prepare(`SELECT COUNT(DISTINCT visitor_id) n FROM analytics_events WHERE created_at>=? AND visitor_id!=''`).bind(since).first(),
 env.DB.prepare(`SELECT COUNT(DISTINCT session_id) n FROM analytics_events WHERE created_at>=? AND session_id!=''`).bind(since).first(),
 env.DB.prepare(`SELECT path,MAX(title) title,COUNT(*) views FROM analytics_events WHERE event_name='page_view' AND created_at>=? GROUP BY path ORDER BY views DESC LIMIT 20`).bind(since).all(),
 env.DB.prepare(`SELECT country,COUNT(DISTINCT visitor_id) visitors FROM analytics_events WHERE created_at>=? AND country!='' GROUP BY country ORDER BY visitors DESC LIMIT 20`).bind(since).all(),
 env.DB.prepare(`SELECT event_name,COUNT(*) count FROM analytics_events WHERE created_at>=? GROUP BY event_name ORDER BY count DESC`).bind(since).all(),
 env.DB.prepare(`SELECT COALESCE(SUM(duration_ms),0) total_ms,COUNT(*) n FROM analytics_events WHERE event_name='engagement' AND created_at>=?`).bind(since).first()
]);return json({success:true,days,summary:{page_views:views?.n||0,unique_visitors:visitors?.n||0,sessions:sessions?.n||0,avg_engagement_ms:duration?.n?Math.round((duration.total_ms||0)/duration.n):0},top_pages:top.results,countries:countries.results,events:events.results})}
function allowedImage(t){return ['image/jpeg','image/png','image/webp','image/gif','image/svg+xml'].includes(t)}
function b64(bytes){let s='';const a=new Uint8Array(bytes);const step=0x8000;for(let i=0;i<a.length;i+=step)s+=String.fromCharCode(...a.subarray(i,i+step));return btoa(s)}
async function upload(request,env){const f=(await request.formData()).get('file');if(!(f instanceof File))return json({success:false,error:'No image file was uploaded.'},400);if(!allowedImage(f.type))return json({success:false,error:'Only JPG, PNG, WebP, GIF and SVG images are allowed.'},400);if(f.size>700*1024)return json({success:false,error:'Image must be 700 KB or smaller. Please resize the image and try again.'},400);const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',key=`articles/${Date.now()}-${crypto.randomUUID()}.${ext}`,data=`data:${f.type};base64,${b64(await f.arrayBuffer())}`;if(data.length>950000)return json({success:false,error:'Image is too large after encoding. Please use a smaller image.'},400);await env.DB.prepare('INSERT INTO media(filename,object_key,mime_type,size,data) VALUES(?,?,?,?,?)').bind(f.name,key,f.type,f.size,data).run();return json({success:true,url:`/api/media/${encodeURIComponent(key)}`,key,filename:f.name})}
async function media(key,env){const o=await env.DB.prepare('SELECT mime_type,data FROM media WHERE object_key=? LIMIT 1').bind(key).first();if(!o||!o.data)return new Response('Image not found',{status:404});const comma=o.data.indexOf(',');const raw=comma>=0?o.data.slice(comma+1):o.data;const bin=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return new Response(bin,{headers:{'Content-Type':o.mime_type,'Cache-Control':'public, max-age=31536000, immutable'}})}
async function assets(request,env){const u=new URL(request.url),r=await env.ASSETS.fetch(request);const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))return r;const text=await r.text();if(!text.toLowerCase().includes('</body>'))return new Response(text,r);let injected='<script src="/figureng-analytics.js" defer></script><script src="/figureng-ads.js" defer></script>';if(u.pathname==='/admin.html')injected+='<style>#figurengAnalyticsLink{position:fixed;right:16px;bottom:16px;z-index:9999;background:#12372a;color:#fff;padding:10px 13px;border-radius:6px;font:800 11px Arial;text-decoration:none;box-shadow:0 4px 14px rgba(0,0,0,.15)}</style><a id="figurengAnalyticsLink" href="/analytics.html">Analytics</a>';const out=text.replace(/<\/body>/i,`${injected}</body>`);const h=new Headers(r.headers);h.delete('content-length');return new Response(out,{status:r.status,statusText:r.statusText,headers:h})}
export default {async fetch(request,env){const u=new URL(request.url),p=u.pathname;try{await ensureCmsTables(env);if(p.startsWith('/api/media/'))return media(decodeURIComponent(p.slice(11)),env);if(p==='/api/analytics'&&request.method==='POST')return analyticsWrite(request,env);if(p==='/api/site-config'&&request.method==='GET')return json({success:true,settings:await settings(env)});if(p==='/api/articles'&&request.method==='GET')return articles(request,env);if(p.startsWith('/api/')){if(!(await auth(request,env)))return noauth();if(p==='/api/analytics'&&request.method==='GET')return analyticsReport(request,env);if(p==='/api/articles'&&request.method==='POST')return create(request,env);if(p==='/api/media'&&request.method==='POST')return upload(request,env);if(p==='/api/site-config'&&request.method==='PUT')return putSettings(request,env);if(p==='/api/ad-settings'&&request.method==='PUT')return putAds(request,env);const m=p.match(/^\/api\/articles\/(\d+)$/);if(m){if(request.method==='GET')return one(m[1],env);if(request.method==='PUT')return update(m[1],request,env);if(request.method==='DELETE')return remove(m[1],env)}}return assets(request,env)}catch(e){return json({success:false,error:e?.message||'Server error.'},500)}}};
